name: test

on:
  pull_request:
    branches: main

permissions:
  contents: write
  # packages: write
  # issues: write
defaults:
  run:
    shell: pwsh

jobs:
  acceptance:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
      - name: Build and Test
        run: |
          ./build.ps1 -Target Test -ErrorAction Stop
      - name: Show `version` output
        run: |
          $fizztool = Get-Command "./dist/fizztool*/fizztool*" -ErrorAction Stop
          & $fizztool version
          & $fizztool version | ConvertFrom-Json
      - name: Show `get` output
        run: |
          $fizztool = Get-Command "./dist/fizztool*/fizztool*" -ErrorAction Stop
          & $fizztool get --key fizz
          & $fizztool get --key fizz | ConvertFrom-Json
