name: test

on:
  pull_request:
    branches: main

permissions:
  contents: write
  # packages: write
  # issues: write
defaults:
  run:
    shell: pwsh

jobs:
  acceptance:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
      - run: |
          ./build.ps1 -Target Test -ErrorAction Stop